### ISSUE TITLE
Bug-Update Unicef logo in the Agency app(Check description)

### ISSUE THREAD

**Issue by santosh-rumsan** [unicef-rumsan/rahat-frontend#66]
https://drive.google.com/file/d/14oxvUl9IkqJtVk2XvpZznt6yQRm9mUeO/view?usp=sharing

**Comment by santosh-rumsan** [comment]
Can you please send transparent version? @bibek-rumsan

**Comment by bibek-rumsan** [comment]
Here you go!
https://drive.google.com/file/d/1ltKDAzn4tsESkKsssH3YZOuCvFyt16dn/view?usp=sharing
